

on:
  pull_request:
    paths:
      - "haikus.json"
      - "haikus.schema.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install ajv-cli

      - name: Validate haikus.json
        run: |
          npx ajv validate -s haikus.schema.json -d haikus.json
